export interface Product {
  id: number;
  slug: string;
  category: string;
  categoryLabel: string;
  name: string;
  specs: string;
  image: string;
  badges: { label: string; color: 'teal' | 'amber' | 'red' }[];
  priceLocked: boolean;
}

export const products: Product[] = [
  {
    id: 1,
    slug: 'aquapro-r32-8kw',
    category: 'aerotermia',
    categoryLabel: 'AEROTERMIa',
    name: 'AQUAPRO R32 8KW',
    specs: 'Monoblock R32, COP 4.2, hasta 60°C',
    image: '/product-aeroterm.jpg',
    badges: [
      { label: '8 kW', color: 'teal' },
      { label: 'COP 4.2', color: 'teal' },
      { label: '60°C', color: 'amber' },
    ],
    priceLocked: true,
  },
  {
    id: 2,
    slug: 'aquapro-r32-12kw',
    category: 'aerotermia',
    categoryLabel: 'AEROTERMIa',
    name: 'AQUAPRO R32 12KW',
    specs: 'Monoblock R32, COP 4.5, hasta 65°C',
    image: '/product-aeroterm.jpg',
    badges: [
      { label: '12 kW', color: 'teal' },
      { label: 'COP 4.5', color: 'teal' },
      { label: '65°C', color: 'amber' },
    ],
    priceLocked: true,
  },
  {
    id: 3,
    slug: 'geomax-15kw',
    category: 'geotermia',
    categoryLabel: 'GEOTERMIa',
    name: 'GEOMAX 15KW',
    specs: 'Loop cerrado, COP 5.1, industrial',
    image: '/product-geoterm.jpg',
    badges: [
      { label: '15 kW', color: 'teal' },
      { label: 'COP 5.1', color: 'teal' },
      { label: 'Industrial', color: 'red' },
    ],
    priceLocked: true,
  },
  {
    id: 4,
    slug: 'acs-pro-300l',
    category: 'acs',
    categoryLabel: 'ACS',
    name: 'ACS PRO 300L',
    specs: 'Acumulacion 300L, serpentin doble, inox',
    image: '/product-acs.jpg',
    badges: [
      { label: '300 L', color: 'teal' },
      { label: 'Inox', color: 'teal' },
      { label: 'Doble serpentin', color: 'amber' },
    ],
    priceLocked: true,
  },
  {
    id: 5,
    slug: 'poolheat-20kw',
    category: 'piscinas',
    categoryLabel: 'PISCINAS',
    name: 'POOLHEAT 20KW',
    specs: 'Titanio intercambiador, 20-35°C, silent',
    image: '/product-piscina.jpg',
    badges: [
      { label: '20 kW', color: 'teal' },
      { label: 'Titanio', color: 'teal' },
      { label: 'Silent', color: 'teal' },
    ],
    priceLocked: true,
  },
  {
    id: 6,
    slug: 'induheat-50kw',
    category: 'industrial',
    categoryLabel: 'INDUSTRIAL',
    name: 'INDUHEAT 50KW',
    specs: 'Cascada, 50-150kW, recuperacion calor',
    image: '/product-industrial.jpg',
    badges: [
      { label: '50-150 kW', color: 'red' },
      { label: 'Cascada', color: 'amber' },
      { label: 'COP 4.8', color: 'teal' },
    ],
    priceLocked: true,
  },
  {
    id: 7,
    slug: 'aquapro-r32-16kw',
    category: 'aerotermia',
    categoryLabel: 'AEROTERMIa',
    name: 'AQUAPRO R32 16KW',
    specs: 'Monoblock R32, COP 4.3, hasta 65°C, trifasica',
    image: '/product-aeroterm.jpg',
    badges: [
      { label: '16 kW', color: 'teal' },
      { label: 'COP 4.3', color: 'teal' },
      { label: '65°C', color: 'amber' },
    ],
    priceLocked: true,
  },
  {
    id: 8,
    slug: 'aquapro-r32-20kw',
    category: 'aerotermia',
    categoryLabel: 'AEROTERMIa',
    name: 'AQUAPRO R32 20KW',
    specs: 'Monoblock R32, COP 4.1, 62°C, comercial',
    image: '/product-aeroterm.jpg',
    badges: [
      { label: '20 kW', color: 'teal' },
      { label: 'COP 4.1', color: 'teal' },
      { label: 'Comercial', color: 'red' },
    ],
    priceLocked: true,
  },
  {
    id: 9,
    slug: 'aquapro-r410a-12kw',
    category: 'aerotermia',
    categoryLabel: 'AEROTERMIa',
    name: 'AQUAPRO R410A 12KW',
    specs: 'Monoblock R410A, COP 4.0, hasta 58°C',
    image: '/product-aeroterm.jpg',
    badges: [
      { label: '12 kW', color: 'teal' },
      { label: 'COP 4.0', color: 'teal' },
      { label: '58°C', color: 'amber' },
    ],
    priceLocked: true,
  },
  {
    id: 10,
    slug: 'aquapro-r410a-16kw',
    category: 'aerotermia',
    categoryLabel: 'AEROTERMIa',
    name: 'AQUAPRO R410A 16KW',
    specs: 'Monoblock R410A, COP 3.9, 58°C, trifasica',
    image: '/product-aeroterm.jpg',
    badges: [
      { label: '16 kW', color: 'teal' },
      { label: 'COP 3.9', color: 'amber' },
      { label: '58°C', color: 'amber' },
    ],
    priceLocked: true,
  },
  {
    id: 11,
    slug: 'aquapro-split-8kw',
    category: 'aerotermia',
    categoryLabel: 'AEROTERMIa',
    name: 'AQUAPRO SPLIT 8KW',
    specs: 'Split R32, COP 4.4, 55°C, ultra silencioso',
    image: '/product-aeroterm.jpg',
    badges: [
      { label: '8 kW', color: 'teal' },
      { label: 'COP 4.4', color: 'teal' },
      { label: '42 dB', color: 'teal' },
    ],
    priceLocked: true,
  },
  {
    id: 12,
    slug: 'aquapro-split-12kw',
    category: 'aerotermia',
    categoryLabel: 'AEROTERMIa',
    name: 'AQUAPRO SPLIT 12KW',
    specs: 'Split R32, COP 4.3, 55°C, ultra silencioso',
    image: '/product-aeroterm.jpg',
    badges: [
      { label: '12 kW', color: 'teal' },
      { label: 'COP 4.3', color: 'teal' },
      { label: '45 dB', color: 'teal' },
    ],
    priceLocked: true,
  },
  {
    id: 13,
    slug: 'geomax-25kw',
    category: 'geotermia',
    categoryLabel: 'GEOTERMIa',
    name: 'GEOMAX 25KW',
    specs: 'Loop cerrado, COP 4.9, comercial',
    image: '/product-geoterm.jpg',
    badges: [
      { label: '25 kW', color: 'teal' },
      { label: 'COP 4.9', color: 'teal' },
      { label: 'Comercial', color: 'red' },
    ],
    priceLocked: true,
  },
  {
    id: 14,
    slug: 'geomax-40kw',
    category: 'geotermia',
    categoryLabel: 'GEOTERMIa',
    name: 'GEOMAX 40KW',
    specs: 'Loop abierto, COP 4.7, 70°C salida',
    image: '/product-geoterm.jpg',
    badges: [
      { label: '40 kW', color: 'teal' },
      { label: 'COP 4.7', color: 'teal' },
      { label: '70°C', color: 'amber' },
    ],
    priceLocked: true,
  },
  {
    id: 15,
    slug: 'geomax-cascade-50kw',
    category: 'geotermia',
    categoryLabel: 'GEOTERMIa',
    name: 'GEOCASCADA 50KW',
    specs: 'Cascada modular, COP 4.5, gran volumen',
    image: '/product-geoterm.jpg',
    badges: [
      { label: '50 kW', color: 'red' },
      { label: 'Cascada', color: 'amber' },
      { label: 'COP 4.5', color: 'teal' },
    ],
    priceLocked: true,
  },
  {
    id: 16,
    slug: 'acs-pro-200l',
    category: 'acs',
    categoryLabel: 'ACS',
    name: 'ACS PRO 200L',
    specs: 'Acumulacion 200L, serpentin simple, inox',
    image: '/product-acs.jpg',
    badges: [
      { label: '200 L', color: 'teal' },
      { label: 'Inox 316', color: 'teal' },
      { label: 'Simple', color: 'amber' },
    ],
    priceLocked: true,
  },
  {
    id: 17,
    slug: 'acs-pro-500l',
    category: 'acs',
    categoryLabel: 'ACS',
    name: 'ACS PRO 500L',
    specs: 'Acumulacion 500L, serpentin doble, inox',
    image: '/product-acs.jpg',
    badges: [
      { label: '500 L', color: 'teal' },
      { label: 'Inox 316', color: 'teal' },
      { label: 'Doble serpentin', color: 'amber' },
    ],
    priceLocked: true,
  },
  {
    id: 18,
    slug: 'poolheat-12kw',
    category: 'piscinas',
    categoryLabel: 'PISCINAS',
    name: 'POOLHEAT 12KW',
    specs: 'Titanio intercambiador, 20-32°C, 6m3/h',
    image: '/product-piscina.jpg',
    badges: [
      { label: '12 kW', color: 'teal' },
      { label: 'Titanio', color: 'teal' },
      { label: 'COP 5.8', color: 'teal' },
    ],
    priceLocked: true,
  },
  {
    id: 19,
    slug: 'poolheat-35kw',
    category: 'piscinas',
    categoryLabel: 'PISCINAS',
    name: 'POOLHEAT 35KW',
    specs: 'Titanio + inverter, 20-38°C, piscinas grandes',
    image: '/product-piscina.jpg',
    badges: [
      { label: '35 kW', color: 'red' },
      { label: 'Inverter', color: 'teal' },
      { label: 'Titanio', color: 'teal' },
    ],
    priceLocked: true,
  },
  {
    id: 20,
    slug: 'inducascade-150kw',
    category: 'industrial',
    categoryLabel: 'INDUSTRIAL',
    name: 'INDUCASCADA 150KW',
    specs: 'Gran volumen, COP 3.8, 80°C salida',
    image: '/product-industrial.jpg',
    badges: [
      { label: '150 kW', color: 'red' },
      { label: 'Cascada', color: 'amber' },
      { label: '80°C', color: 'amber' },
    ],
    priceLocked: true,
  },
];

export interface Stat {
  number: string;
  numericValue: number;
  prefix: string;
  suffix: string;
  label: string;
}

export const stats: Stat[] = [
  { number: '4.8x', numericValue: 4.8, prefix: '', suffix: 'x', label: 'COP PROMEDIO' },
  { number: '70%', numericValue: 70, prefix: '', suffix: '%', label: 'AHORRO ENERGETICO' },
  { number: '1,200+', numericValue: 1200, prefix: '', suffix: '+', label: 'INSTALACIONES EN LATAM' },
  { number: '5', numericValue: 5, prefix: '', suffix: '', label: 'PAISES CON COBERTURA' },
];

export interface FeatureCard {
  icon: string;
  iconBg: string;
  iconColor: string;
  title: string;
  description: string;
}

export const featureCards: FeatureCard[] = [
  {
    icon: 'Tag',
    iconBg: 'rgba(230,57,70,0.1)',
    iconColor: '#e63946',
    title: 'PRECIOS EXCLUSIVOS',
    description: 'Registrate como distribuidor para acceder a lista de precios con descuentos de hasta 40% sobre precio de instalador.',
  },
  {
    icon: 'GraduationCap',
    iconBg: 'rgba(42,157,143,0.1)',
    iconColor: '#2a9d8f',
    title: 'FORMACION CERTIFICADA',
    description: 'Capacitacion tecnica online y presencial: seleccion, instalacion, puesta en marcha y servicio post-venta de cada equipo.',
  },
  {
    icon: 'Headphones',
    iconBg: 'rgba(21,72,160,0.1)',
    iconColor: '#022067',
    title: 'SOPORTE INTEGRAL',
    description: 'Equipo de ingenieria a tu disposicion: seleccion de equipos, diseno de instalacion, calculos de ahorro y atencion post-venta.',
  },
];

export const marqueeWords = [
  'AEROTERMO',
  'COP 4.8',
  'DISTRIBUIDOR',
  'AHORRO 70%',
  'GEOTERIA',
  'REGISTRESE',
];

export const certifications = ['ISO 9001', 'CE', 'ERP', 'Keymark', 'Eurovent'];

export const regions = ['Chile', 'Mexico', 'Colombia', 'Peru', 'Argentina'];

export const navLinks = [
  { label: 'PRODUCTOS', path: '/productos' },
  { label: 'DISTRIBUIDOR', path: '/distribuidor' },
  { label: 'HERRAMIENTAS', path: '/herramientas' },
  { label: 'CASOS', path: '/casos' },
  { label: 'NOSOTROS', path: '/nosotros' },
  { label: 'CONTACTO', path: '/contacto' },
];

export const distributorBenefits = [
  'Precios exclusivos',
  'Formacion certificada',
  'Soporte tecnico 24/7',
  'Herramientas de venta',
  'Garantia extendida',
  'Leads de tu zona',
];

/* ────────────────────────
   Category Filters
   ──────────────────────── */
export const categoryFilters = [
  { key: 'todos', label: 'TODOS' },
  { key: 'aerotermia', label: 'AEROTERMIa' },
  { key: 'geotermia', label: 'GEOTERMIa' },
  { key: 'acs', label: 'ACS' },
  { key: 'industrial', label: 'INDUSTRIAL' },
  { key: 'piscinas', label: 'PISCINAS' },
] as const;

/* ────────────────────────
   Extended Product Data for Detail Pages
   ──────────────────────── */
export interface ProductDetail {
  slug: string;
  subtitle: string;
  gallery: string[];
  quickSpecs: { label: string; value: string }[];
  benefits: { icon: string; title: string; description: string }[];
  docs: { name: string; format: string; size: string }[];
  relatedSlugs: string[];
}

export const productDetails: Record<string, ProductDetail> = {
  'aquapro-r32-8kw': {
    slug: 'aquapro-r32-8kw',
    subtitle: 'Bomba de calor monoblock R32 para climatizacion y ACS residencial',
    gallery: ['/product-aeroterm.jpg', '/product-aeroterm.jpg', '/product-aeroterm.jpg'],
    quickSpecs: [
      { label: 'Potencia termica', value: '8 kW' },
      { label: 'COP (A7/W35)', value: '4.2' },
      { label: 'Refrigerante', value: 'R32' },
      { label: 'Temperatura max. salida', value: '60°C' },
      { label: 'Tension', value: '230V / 1Ph / 50Hz' },
      { label: 'Nivel sonoro', value: '45 dB(A)' },
      { label: 'Peso', value: '68 kg' },
      { label: 'Dimensiones', value: '980 x 420 x 780 mm' },
      { label: 'Garantia', value: '5 anos' },
    ],
    benefits: [
      { icon: 'Zap', title: 'AHORRO 70%', description: 'Reduce el consumo energetico hasta un 70% comparado con sistemas de resistencia electrica convencional.' },
      { icon: 'Clock', title: 'INSTALACION 1 DIA', description: 'Unidad monoblock compacta que permite una instalacion rapida y sencilla en una sola jornada.' },
      { icon: 'Thermometer', title: 'FUNCIONA HASTA -15°C', description: 'Opera eficientemente en temperaturas exteriores de hasta -15°C, ideal para climas variados de Latinoamerica.' },
      { icon: 'Wrench', title: 'MANTENIMIENTO MINIMO', description: 'Diseno robusto con compresor inverter que reduce el desgaste y requiere solo revision anual.' },
      { icon: 'Calendar', title: 'VIDA UTIL 15+ ANOS', description: 'Construccion en acero inoxidable y componentes de primera calidad para una vida util superior a 15 anos.' },
    ],
    docs: [
      { name: 'Ficha Tecnica AquaPro R32 8kW', format: 'PDF', size: '2.4 MB' },
      { name: 'Manual de Instalacion', format: 'PDF', size: '5.1 MB' },
      { name: 'Manual de Usuario', format: 'PDF', size: '1.8 MB' },
      { name: 'Certificado CE', format: 'PDF', size: '0.5 MB' },
      { name: 'Dimensiones y Conexiones (DWG)', format: 'DWG', size: '1.2 MB' },
    ],
    relatedSlugs: ['aquapro-r32-12kw', 'aquapro-r32-16kw', 'aquapro-split-8kw'],
  },
  'aquapro-r32-12kw': {
    slug: 'aquapro-r32-12kw',
    subtitle: 'Bomba de calor monoblock R32 para climatizacion y ACS residencial de mayor demanda',
    gallery: ['/product-aeroterm.jpg', '/product-aeroterm.jpg', '/product-aeroterm.jpg'],
    quickSpecs: [
      { label: 'Potencia termica', value: '12 kW' },
      { label: 'COP (A7/W35)', value: '4.5' },
      { label: 'Refrigerante', value: 'R32' },
      { label: 'Temperatura max. salida', value: '65°C' },
      { label: 'Tension', value: '230V / 1Ph / 50Hz' },
      { label: 'Nivel sonoro', value: '48 dB(A)' },
      { label: 'Peso', value: '85 kg' },
      { label: 'Dimensiones', value: '1100 x 450 x 850 mm' },
      { label: 'Garantia', value: '5 anos' },
    ],
    benefits: [
      { icon: 'Zap', title: 'COP 4.5', description: 'Relacion de eficiencia energetica que se traduce en hasta un 70% de ahorro comparado con sistemas de resistencia electrica.' },
      { icon: 'Box', title: 'MONOBLOCK COMPACTO', description: 'Unidad unica para exteriores. Sin necesidad de conexion frigorifica interna. Instalacion simplificada y menor costo de mano de obra.' },
      { icon: 'Thermometer', title: '65°C DE SALIDA', description: 'Temperatura suficiente para radiadores tradicionales y sistemas de aerotermia de alta temperatura.' },
      { icon: 'VolumeX', title: 'SILENCIOSO', description: '48 dB(A) a 1 metro. Compresor inverter con modulacion de velocidad que reduce ruido en cargas parciales.' },
      { icon: 'Shield', title: 'GARANTIA 5 ANOS', description: 'Garantia completa del compresor y componentes. Extensible a 7 anos para distribuidores certificados.' },
    ],
    docs: [
      { name: 'Ficha Tecnica AquaPro R32 12kW', format: 'PDF', size: '2.6 MB' },
      { name: 'Manual de Instalacion', format: 'PDF', size: '5.3 MB' },
      { name: 'Manual de Usuario', format: 'PDF', size: '1.9 MB' },
      { name: 'Certificado CE', format: 'PDF', size: '0.5 MB' },
      { name: 'Dimensiones y Conexiones (DWG)', format: 'DWG', size: '1.3 MB' },
    ],
    relatedSlugs: ['aquapro-r32-8kw', 'aquapro-r32-16kw', 'aquapro-r410a-12kw'],
  },
  'aquapro-r32-16kw': {
    slug: 'aquapro-r32-16kw',
    subtitle: 'Bomba de calor monoblock R32 de alta potencia para residencias grandes y comercios pequenos',
    gallery: ['/product-aeroterm.jpg', '/product-aeroterm.jpg', '/product-aeroterm.jpg'],
    quickSpecs: [
      { label: 'Potencia termica', value: '16 kW' },
      { label: 'COP (A7/W35)', value: '4.3' },
      { label: 'Refrigerante', value: 'R32' },
      { label: 'Temperatura max. salida', value: '65°C' },
      { label: 'Tension', value: '400V / 3Ph / 50Hz' },
      { label: 'Nivel sonoro', value: '52 dB(A)' },
      { label: 'Peso', value: '112 kg' },
      { label: 'Dimensiones', value: '1250 x 520 x 920 mm' },
      { label: 'Garantia', value: '5 anos' },
    ],
    benefits: [
      { icon: 'Zap', title: 'ALTA POTENCIA', description: '16 kW de potencia termica para cubrir grandes espacios residenciales y pequenos comercios con eficiencia.' },
      { icon: 'Box', title: 'REFRIGERANTE R32', description: 'Menor potencial de calentamiento global y mayor eficiencia que R410A. Carga reducida y compatible con normativa europea 2025.' },
      { icon: 'Thermometer', title: 'FUNCIONA HASTA -20°C', description: 'Diseño reforzado que mantiene el rendimiento en temperaturas exteriores de hasta -20°C.' },
      { icon: 'Wrench', title: 'MANTENIMIENTO MINIMO', description: 'Compresor inverter de doble rotor que reduce vibraciones y desgaste mecanico para mayor vida util.' },
      { icon: 'Shield', title: 'VIDA UTIL 15+ ANOS', description: 'Intercambiador de placas soldadas en acero inoxidable 316L resistente a la corrosion.' },
    ],
    docs: [
      { name: 'Ficha Tecnica AquaPro R32 16kW', format: 'PDF', size: '2.5 MB' },
      { name: 'Manual de Instalacion', format: 'PDF', size: '5.8 MB' },
      { name: 'Manual de Usuario', format: 'PDF', size: '2.1 MB' },
      { name: 'Certificado CE', format: 'PDF', size: '0.5 MB' },
      { name: 'Dimensiones y Conexiones (DWG)', format: 'DWG', size: '1.4 MB' },
    ],
    relatedSlugs: ['aquapro-r32-12kw', 'aquapro-r32-20kw', 'aquapro-r410a-16kw'],
  },
  'aquapro-r32-20kw': {
    slug: 'aquapro-r32-20kw',
    subtitle: 'Bomba de calor monoblock R32 de potencia comercial para grandes instalaciones',
    gallery: ['/product-aeroterm.jpg', '/product-aeroterm.jpg', '/product-aeroterm.jpg'],
    quickSpecs: [
      { label: 'Potencia termica', value: '20 kW' },
      { label: 'COP (A7/W35)', value: '4.1' },
      { label: 'Refrigerante', value: 'R32' },
      { label: 'Temperatura max. salida', value: '62°C' },
      { label: 'Tension', value: '400V / 3Ph / 50Hz' },
      { label: 'Nivel sonoro', value: '54 dB(A)' },
      { label: 'Peso', value: '138 kg' },
      { label: 'Dimensiones', value: '1380 x 560 x 980 mm' },
      { label: 'Garantia', value: '5 anos' },
    ],
    benefits: [
      { icon: 'Zap', title: 'POTENCIA COMERCIAL', description: '20 kW para climatizar espacios comerciales, oficinas y residencias de gran tamano con maxima eficiencia.' },
      { icon: 'Box', title: 'CASCADA MODULAR', description: 'Compatible con control de cascada para instalar multiples unidades trabajando en conjunto.' },
      { icon: 'Thermometer', title: 'FUNCIONA HASTA -20°C', description: 'Mantiene el 75% de la potencia nominal a -15°C exterior gracias a su compresor de alta cilindrada.' },
      { icon: 'Wrench', title: 'MANTENIMIENTO REMOTO', description: 'Conectividad WiFi opcional para monitoreo remoto y diagnostico preventivo del equipo.' },
      { icon: 'Shield', title: 'GARANTIA 5 ANOS', description: 'Cobertura completa en compresor, placa de control e intercambiador de calor.' },
    ],
    docs: [
      { name: 'Ficha Tecnica AquaPro R32 20kW', format: 'PDF', size: '2.8 MB' },
      { name: 'Manual de Instalacion', format: 'PDF', size: '6.2 MB' },
      { name: 'Manual de Usuario', format: 'PDF', size: '2.2 MB' },
      { name: 'Certificado CE', format: 'PDF', size: '0.6 MB' },
      { name: 'Dimensiones y Conexiones (DWG)', format: 'DWG', size: '1.5 MB' },
    ],
    relatedSlugs: ['aquapro-r32-16kw', 'aquapro-r410a-16kw', 'induheat-50kw'],
  },
  'aquapro-r410a-12kw': {
    slug: 'aquapro-r410a-12kw',
    subtitle: 'Bomba de calor monoblock R410A confiable y probada en instalaciones residenciales',
    gallery: ['/product-aeroterm.jpg', '/product-aeroterm.jpg', '/product-aeroterm.jpg'],
    quickSpecs: [
      { label: 'Potencia termica', value: '12 kW' },
      { label: 'COP (A7/W35)', value: '4.0' },
      { label: 'Refrigerante', value: 'R410A' },
      { label: 'Temperatura max. salida', value: '58°C' },
      { label: 'Tension', value: '230V / 1Ph / 50Hz' },
      { label: 'Nivel sonoro', value: '47 dB(A)' },
      { label: 'Peso', value: '78 kg' },
      { label: 'Dimensiones', value: '1050 x 430 x 820 mm' },
      { label: 'Garantia', value: '5 anos' },
    ],
    benefits: [
      { icon: 'Zap', title: 'TECNOLOGIA PROBADA', description: 'Refrigerante R410A con anos de trayectoria y amplia red de soporte tecnico en toda Latinoamerica.' },
      { icon: 'Box', title: 'INSTALACION 1 DIA', description: 'Diseno monoblock que agiliza la instalacion y reduce costos de mano de obra y materiales.' },
      { icon: 'Thermometer', title: 'FUNCIONA HASTA -10°C', description: 'Rendimiento optimo en climas templados y tropicales de Latinoamerica.' },
      { icon: 'Wrench', title: 'MANTENIMIENTO MINIMO', description: 'Compresor scroll de alta fiabilidad con arranque suave que prolonga la vida util del equipo.' },
      { icon: 'Shield', title: 'VIDA UTIL 15+ ANOS', description: 'Construccion robusta con proteccion anticorrosiva para operacion en ambientes costeros.' },
    ],
    docs: [
      { name: 'Ficha Tecnica AquaPro R410A 12kW', format: 'PDF', size: '2.3 MB' },
      { name: 'Manual de Instalacion', format: 'PDF', size: '4.9 MB' },
      { name: 'Manual de Usuario', format: 'PDF', size: '1.7 MB' },
      { name: 'Certificado CE', format: 'PDF', size: '0.5 MB' },
    ],
    relatedSlugs: ['aquapro-r32-12kw', 'aquapro-r410a-16kw', 'aquapro-r32-8kw'],
  },
  'aquapro-r410a-16kw': {
    slug: 'aquapro-r410a-16kw',
    subtitle: 'Bomba de calor monoblock R410A de mayor potencia para instalaciones residenciales y comerciales',
    gallery: ['/product-aeroterm.jpg', '/product-aeroterm.jpg', '/product-aeroterm.jpg'],
    quickSpecs: [
      { label: 'Potencia termica', value: '16 kW' },
      { label: 'COP (A7/W35)', value: '3.9' },
      { label: 'Refrigerante', value: 'R410A' },
      { label: 'Temperatura max. salida', value: '58°C' },
      { label: 'Tension', value: '400V / 3Ph / 50Hz' },
      { label: 'Nivel sonoro', value: '51 dB(A)' },
      { label: 'Peso', value: '105 kg' },
      { label: 'Dimensiones', value: '1200 x 490 x 900 mm' },
      { label: 'Garantia', value: '5 anos' },
    ],
    benefits: [
      { icon: 'Zap', title: 'POTENCIA VERSATIL', description: '16 kW ideales para viviendas unifamiliares, locales comerciales y pequenas oficinas.' },
      { icon: 'Box', title: 'COMPRESOR DUAL', description: 'Sistema de doble compresor scroll para mayor redundancia y operacion parcial eficiente.' },
      { icon: 'Thermometer', title: 'FUNCIONA HASTA -10°C', description: 'Rendimiento confiable en las condiciones climaticas mas comunes de Latinoamerica.' },
      { icon: 'Wrench', title: 'DIAGNOSTICO INTELIGENTE', description: 'Placa de control con autodiagnostico y visualizacion de codigos de error en display LED.' },
      { icon: 'Shield', title: 'GARANTIA 5 ANOS', description: 'Soporte tecnico y stock de repuestos garantizados en Chile, Mexico, Colombia y Peru.' },
    ],
    docs: [
      { name: 'Ficha Tecnica AquaPro R410A 16kW', format: 'PDF', size: '2.5 MB' },
      { name: 'Manual de Instalacion', format: 'PDF', size: '5.4 MB' },
      { name: 'Manual de Usuario', format: 'PDF', size: '1.9 MB' },
      { name: 'Certificado CE', format: 'PDF', size: '0.5 MB' },
    ],
    relatedSlugs: ['aquapro-r410a-12kw', 'aquapro-r32-16kw', 'geomax-15kw'],
  },
  'aquapro-split-8kw': {
    slug: 'aquapro-split-8kw',
    subtitle: 'Bomba de calor split R32 con unidad exterior separada para instalaciones versatiles',
    gallery: ['/product-aeroterm.jpg', '/product-aeroterm.jpg', '/product-aeroterm.jpg'],
    quickSpecs: [
      { label: 'Potencia termica', value: '8 kW' },
      { label: 'COP (A7/W35)', value: '4.4' },
      { label: 'Refrigerante', value: 'R32' },
      { label: 'Temperatura max. salida', value: '55°C' },
      { label: 'Tension', value: '230V / 1Ph / 50Hz' },
      { label: 'Nivel sonoro', value: '42 dB(A)' },
      { label: 'Peso (ext.)', value: '45 kg' },
      { label: 'Dimensiones (ext.)', value: '850 x 320 x 650 mm' },
      { label: 'Garantia', value: '5 anos' },
    ],
    benefits: [
      { icon: 'VolumeX', title: 'ULTRA SILENCIOSO', description: 'Solo 42 dB(A) gracias a la unidad exterior separada. Ideal para zonas residenciales con restricciones de ruido.' },
      { icon: 'Box', title: 'INSTALACION FLEXIBLE', description: 'La unidad exterior se puede instalar hasta 20m de distancia, permitiendo mayor flexibilidad de diseno.' },
      { icon: 'Thermometer', title: 'FUNCIONA HASTA -15°C', description: 'Mantiene rendimiento optimo en invierno gracias al refrigerante R32 y compresor inverter.' },
      { icon: 'Wrench', title: 'MANTENIMIENTO LOCALIZADO', description: 'El acceso a componentes esta centralizado en la unidad exterior, facilitando el servicio tecnico.' },
      { icon: 'Shield', title: 'VIDA UTIL 15+ ANOS', description: 'Tuberias de cobre con aislamiento termico de alta densidad para minima perdida de eficiencia.' },
    ],
    docs: [
      { name: 'Ficha Tecnica AquaPro Split 8kW', format: 'PDF', size: '2.2 MB' },
      { name: 'Manual de Instalacion', format: 'PDF', size: '4.8 MB' },
      { name: 'Manual de Usuario', format: 'PDF', size: '1.6 MB' },
      { name: 'Certificado CE', format: 'PDF', size: '0.5 MB' },
    ],
    relatedSlugs: ['aquapro-split-12kw', 'aquapro-r32-8kw', 'aquapro-r32-12kw'],
  },
  'aquapro-split-12kw': {
    slug: 'aquapro-split-12kw',
    subtitle: 'Bomba de calor split R32 de mayor capacidad con unidad exterior independiente',
    gallery: ['/product-aeroterm.jpg', '/product-aeroterm.jpg', '/product-aeroterm.jpg'],
    quickSpecs: [
      { label: 'Potencia termica', value: '12 kW' },
      { label: 'COP (A7/W35)', value: '4.3' },
      { label: 'Refrigerante', value: 'R32' },
      { label: 'Temperatura max. salida', value: '55°C' },
      { label: 'Tension', value: '230V / 1Ph / 50Hz' },
      { label: 'Nivel sonoro', value: '45 dB(A)' },
      { label: 'Peso (ext.)', value: '62 kg' },
      { label: 'Dimensiones (ext.)', value: '950 x 380 x 720 mm' },
      { label: 'Garantia', value: '5 anos' },
    ],
    benefits: [
      { icon: 'Zap', title: 'EFICIENCIA SUPERIOR', description: 'COP 4.3 que garantiza minimos costos operativos durante toda la vida util del equipo.' },
      { icon: 'Box', title: 'ULTRA SILENCIOSO', description: 'La separacion de unidades permite ubicar el compresor lejos de zonas de reposo y descanso.' },
      { icon: 'Thermometer', title: 'FUNCIONA HASTA -15°C', description: 'Rendimiento sostenido en climas frios con proteccion anti-hielo integrada.' },
      { icon: 'Wrench', title: 'INSTALACION SIMPLIFICADA', description: 'Conexion frigorifica rapida con acoplamientos de servicio y cableado de control incluido.' },
      { icon: 'Shield', title: 'GARANTIA 5 ANOS', description: 'Cobertura extendida disponible para instaladores certificados en el programa distribuidor.' },
    ],
    docs: [
      { name: 'Ficha Tecnica AquaPro Split 12kW', format: 'PDF', size: '2.4 MB' },
      { name: 'Manual de Instalacion', format: 'PDF', size: '5.0 MB' },
      { name: 'Manual de Usuario', format: 'PDF', size: '1.7 MB' },
      { name: 'Certificado CE', format: 'PDF', size: '0.5 MB' },
    ],
    relatedSlugs: ['aquapro-split-8kw', 'aquapro-r32-12kw', 'aquapro-r410a-12kw'],
  },
  'geomax-15kw': {
    slug: 'geomax-15kw',
    subtitle: 'Bomba de calor geotermica de loop cerrado para maxima eficiencia todo el ano',
    gallery: ['/product-geoterm.jpg', '/product-geoterm.jpg', '/product-geoterm.jpg'],
    quickSpecs: [
      { label: 'Potencia termica', value: '15 kW' },
      { label: 'COP (A7/W35)', value: '5.1' },
      { label: 'Tipo de captacion', value: 'Loop cerrado' },
      { label: 'Temperatura max. salida', value: '65°C' },
      { label: 'Tension', value: '400V / 3Ph / 50Hz' },
      { label: 'Nivel sonoro', value: '44 dB(A)' },
      { label: 'Peso', value: '95 kg' },
      { label: 'Dimensiones', value: '1150 x 480 x 880 mm' },
      { label: 'Garantia', value: '5 anos' },
    ],
    benefits: [
      { icon: 'Zap', title: 'COP 5.1 MAXIMA EFICIENCIA', description: 'El mejor COP de la linea gracias a la estabilidad termica del subsuelo. Ahorros superiores al 75%.' },
      { icon: 'Box', title: 'FUNCIONAMIENTO TODO EL ANO', description: 'La temperatura del terreno es estable todo el ano, garantizando rendimiento constante sin importar el clima.' },
      { icon: 'VolumeX', title: 'ULTRA SILENCIOSO', description: '44 dB(A) al no necesitar ventilador exterior. Ideal para zonas con restricciones de ruido estrictas.' },
      { icon: 'Wrench', title: 'VIDA UTIL 20+ ANOS', description: 'El intercambiador de loop terrestre tiene una vida util de mas de 50 anos y el equipo de 20+ anos.' },
      { icon: 'Shield', title: 'MANTENIMIENTO MINIMO', description: 'Al estar protegido del clima exterior, el equipo sufre menos desgaste y requiere menos mantenimiento.' },
    ],
    docs: [
      { name: 'Ficha Tecnica GeoMax 15kW', format: 'PDF', size: '3.1 MB' },
      { name: 'Manual de Instalacion', format: 'PDF', size: '6.5 MB' },
      { name: 'Manual de Diseno de Loop', format: 'PDF', size: '4.2 MB' },
      { name: 'Certificado CE', format: 'PDF', size: '0.6 MB' },
    ],
    relatedSlugs: ['geomax-25kw', 'aquapro-r32-16kw', 'geomax-40kw'],
  },
  'geomax-25kw': {
    slug: 'geomax-25kw',
    subtitle: 'Bomba de calor geotermica de loop cerrado para aplicaciones comerciales y residenciales grandes',
    gallery: ['/product-geoterm.jpg', '/product-geoterm.jpg', '/product-geoterm.jpg'],
    quickSpecs: [
      { label: 'Potencia termica', value: '25 kW' },
      { label: 'COP (A7/W35)', value: '4.9' },
      { label: 'Tipo de captacion', value: 'Loop cerrado' },
      { label: 'Temperatura max. salida', value: '65°C' },
      { label: 'Tension', value: '400V / 3Ph / 50Hz' },
      { label: 'Nivel sonoro', value: '46 dB(A)' },
      { label: 'Peso', value: '135 kg' },
      { label: 'Dimensiones', value: '1300 x 520 x 960 mm' },
      { label: 'Garantia', value: '5 anos' },
    ],
    benefits: [
      { icon: 'Zap', title: 'EFICIENCIA CONSTANTE', description: 'COP 4.9 estable durante todo el ano sin las fluctuaciones de las fuentes de aire exterior.' },
      { icon: 'Box', title: 'POTENCIA COMERCIAL', description: '25 kW para edificios comerciales, hoteles pequenos, conjuntos residenciales y aplicaciones industriales ligeras.' },
      { icon: 'VolumeX', title: 'SILENCIOSO TOTAL', description: 'Sin unidad exterior ni ventilador. El equipo puede instalarse en cuartos tecnicos interiores o sotanos.' },
      { icon: 'Wrench', title: 'CASCADA MODULAR', description: 'Control de cascada para operar hasta 6 unidades en paralelo segun la demanda termica del edificio.' },
      { icon: 'Shield', title: 'VIDA UTIL 20+ ANOS', description: 'Intercambiadores de placas soldadas y compresores scroll de alta durabilidad para decadas de operacion.' },
    ],
    docs: [
      { name: 'Ficha Tecnica GeoMax 25kW', format: 'PDF', size: '3.3 MB' },
      { name: 'Manual de Instalacion', format: 'PDF', size: '7.1 MB' },
      { name: 'Manual de Diseno de Loop', format: 'PDF', size: '4.5 MB' },
      { name: 'Certificado CE', format: 'PDF', size: '0.6 MB' },
    ],
    relatedSlugs: ['geomax-15kw', 'geomax-40kw', 'geomax-cascade-50kw'],
  },
  'geomax-40kw': {
    slug: 'geomax-40kw',
    subtitle: 'Bomba de calor geotermica de loop abierto para grandes aplicaciones comerciales e industriales',
    gallery: ['/product-geoterm.jpg', '/product-geoterm.jpg', '/product-geoterm.jpg'],
    quickSpecs: [
      { label: 'Potencia termica', value: '40 kW' },
      { label: 'COP (A7/W35)', value: '4.7' },
      { label: 'Tipo de captacion', value: 'Loop abierto' },
      { label: 'Temperatura max. salida', value: '70°C' },
      { label: 'Tension', value: '400V / 3Ph / 50Hz' },
      { label: 'Nivel sonoro', value: '50 dB(A)' },
      { label: 'Peso', value: '185 kg' },
      { label: 'Dimensiones', value: '1450 x 580 x 1100 mm' },
      { label: 'Garantia', value: '5 anos' },
    ],
    benefits: [
      { icon: 'Zap', title: 'MAXIMA POTENCIA GEOTERMICA', description: '40 kW con loop abierto para grandes instalaciones comerciales, hoteles y aplicaciones industriales.' },
      { icon: 'Box', title: 'LOOP ABIERTO EFICIENTE', description: 'Utiliza pozos de agua o fuentes superficiales con mayor eficiencia termica que los loops cerrados.' },
      { icon: 'Thermometer', title: '70°C DE SALIDA', description: 'Temperatura de salida de hasta 70°C, compatible con sistemas de calefaccion de alta temperatura.' },
      { icon: 'Wrench', title: 'CONTROL AVANZADO', description: 'Sistema de control tactil con programacion horaria, monitorizacion remota y diagnostico predictivo.' },
      { icon: 'Shield', title: 'VIDA UTIL 20+ ANOS', description: 'Construccion industrial con intercambiador de placas de titanio para aguas agresivas.' },
    ],
    docs: [
      { name: 'Ficha Tecnica GeoMax 40kW', format: 'PDF', size: '3.5 MB' },
      { name: 'Manual de Instalacion', format: 'PDF', size: '7.8 MB' },
      { name: 'Manual de Diseno de Loop', format: 'PDF', size: '4.8 MB' },
      { name: 'Certificado CE', format: 'PDF', size: '0.7 MB' },
    ],
    relatedSlugs: ['geomax-25kw', 'geomax-cascade-50kw', 'induheat-50kw'],
  },
  'geomax-cascade-50kw': {
    slug: 'geomax-cascade-50kw',
    subtitle: 'Sistema geotermico en cascada de 50kW para aplicaciones de gran volumen',
    gallery: ['/product-geoterm.jpg', '/product-geoterm.jpg', '/product-geoterm.jpg'],
    quickSpecs: [
      { label: 'Potencia termica', value: '50 kW' },
      { label: 'COP (A7/W35)', value: '4.5' },
      { label: 'Tipo de captacion', value: 'Cascada' },
      { label: 'Temperatura max. salida', value: '70°C' },
      { label: 'Tension', value: '400V / 3Ph / 50Hz' },
      { label: 'Nivel sonoro', value: '52 dB(A)' },
      { label: 'Peso', value: '220 kg' },
      { label: 'Dimensiones', value: '1600 x 650 x 1200 mm' },
      { label: 'Garantia', value: '5 anos' },
    ],
    benefits: [
      { icon: 'Zap', title: 'CASCADA 50 KW', description: 'Sistema de 3 unidades modulares de 50 kW total con gestion inteligente de carga para maxima eficiencia.' },
      { icon: 'Box', title: 'REDUNDANCIA TOTAL', description: 'Si una unidad requiere mantenimiento, las restantes continuan operando con el 66% de la capacidad.' },
      { icon: 'Thermometer', title: 'PARA GRANDES VOLUMENES', description: 'Ideal para hoteles, centros deportivos, edificios de oficinas y procesos industriales con alta demanda.' },
      { icon: 'Wrench', title: 'INSTALACION PROFESIONAL', description: 'Incluye supervision de puesta en marcha por ingeniero certificado y capacitacion del personal de mantenimiento.' },
      { icon: 'Shield', title: 'VIDA UTIL 20+ ANOS', description: 'Diseno industrial con componentes de grado comercial y proteccion IP54 para instalacion en cuartos tecnicos.' },
    ],
    docs: [
      { name: 'Ficha Tecnica GeoCascada 50kW', format: 'PDF', size: '4.2 MB' },
      { name: 'Manual de Instalacion', format: 'PDF', size: '8.5 MB' },
      { name: 'Manual de Control de Cascada', format: 'PDF', size: '3.1 MB' },
      { name: 'Certificado CE', format: 'PDF', size: '0.8 MB' },
    ],
    relatedSlugs: ['geomax-40kw', 'induheat-50kw', 'geomax-25kw'],
  },
  'acs-pro-200l': {
    slug: 'acs-pro-200l',
    subtitle: 'Acumulador de agua caliente sanitaria de 200L con serpentin simple',
    gallery: ['/product-acs.jpg', '/product-acs.jpg', '/product-acs.jpg'],
    quickSpecs: [
      { label: 'Capacidad', value: '200 L' },
      { label: 'Tipo de serpentin', value: 'Simple' },
      { label: 'Material', value: 'Acero inox 316' },
      { label: 'Presion maxima', value: '10 bar' },
      { label: 'Perdidas de carga', value: '45 mbar' },
      { label: 'Aislamiento', value: 'PU 50mm' },
      { label: 'Conexiones', value: 'G 1"' },
      { label: 'Peso vacio', value: '28 kg' },
      { label: 'Garantia', value: '5 anos' },
    ],
    benefits: [
      { icon: 'Droplets', title: 'ACERO INOX 316', description: 'Construccion en acero inoxidable 316 de alta calidad para maxima resistencia a la corrosion y agua potable segura.' },
      { icon: 'Thermometer', title: 'AISLAMIENTO PREMIUM', description: 'Aislamiento de poliuretano de 50mm que mantiene el agua caliente por mas tiempo con minimas perdidas termicas.' },
      { icon: 'Zap', title: 'INSTALACION RAPIDA', description: 'Diseno compacto con conexiones roscadas de 1 pulgada para instalacion directa con bombas de calor.' },
      { icon: 'Shield', title: '5 ANOS GARANTIA', description: 'Garantia completa contra defectos de fabricacion y corrosion. Vida util estimada de 15+ anos.' },
      { icon: 'Wrench', title: 'MANTENIMIENTO MINIMO', description: 'Sin componentes electricos ni piezas moviles. Solo requiere revision periodica del anodo de sacrificio.' },
    ],
    docs: [
      { name: 'Ficha Tecnica ACS Pro 200L', format: 'PDF', size: '1.8 MB' },
      { name: 'Manual de Instalacion', format: 'PDF', size: '3.2 MB' },
      { name: 'Certificado Sanitario', format: 'PDF', size: '0.4 MB' },
    ],
    relatedSlugs: ['acs-pro-300l', 'acs-pro-500l', 'aquapro-r32-8kw'],
  },
  'acs-pro-300l': {
    slug: 'acs-pro-300l',
    subtitle: 'Acumulador de agua caliente sanitaria de 300L con serpentin doble para mayor eficiencia',
    gallery: ['/product-acs.jpg', '/product-acs.jpg', '/product-acs.jpg'],
    quickSpecs: [
      { label: 'Capacidad', value: '300 L' },
      { label: 'Tipo de serpentin', value: 'Doble' },
      { label: 'Material', value: 'Acero inox 316' },
      { label: 'Presion maxima', value: '10 bar' },
      { label: 'Perdidas de carga', value: '38 mbar' },
      { label: 'Aislamiento', value: 'PU 60mm' },
      { label: 'Conexiones', value: 'G 1 1/4"' },
      { label: 'Peso vacio', value: '42 kg' },
      { label: 'Garantia', value: '5 anos' },
    ],
    benefits: [
      { icon: 'Droplets', title: 'DOBLE SERPENTIN', description: 'Intercambiador de doble espiral para maxima superficie de transferencia termica y recuperacion rapida de agua calida.' },
      { icon: 'Thermometer', title: 'AISLAMIENTO REFORZADO', description: '60mm de aislamiento de poliuretano inyectado que garantiza minimas perdidas durante horas de inactividad.' },
      { icon: 'Zap', title: 'CAPACIDAD FAMILIAR', description: '300 litros ideales para familias de 4-6 personas con demanda simultanea de duchas y lavavajillas.' },
      { icon: 'Shield', title: 'INOX 316 CERTIFICADO', description: 'Material certificado para contacto con agua potable segun normativa europea. Sin riesgo de corrosion.' },
      { icon: 'Wrench', title: 'VIDA UTIL 15+ ANOS', description: 'Construccion soldada TIG con prueba hidrostatica individual. Anodo de magnesio de facil reposicion.' },
    ],
    docs: [
      { name: 'Ficha Tecnica ACS Pro 300L', format: 'PDF', size: '2.0 MB' },
      { name: 'Manual de Instalacion', format: 'PDF', size: '3.5 MB' },
      { name: 'Certificado Sanitario', format: 'PDF', size: '0.4 MB' },
    ],
    relatedSlugs: ['acs-pro-200l', 'acs-pro-500l', 'aquapro-r32-12kw'],
  },
  'acs-pro-500l': {
    slug: 'acs-pro-500l',
    subtitle: 'Acumulador de agua caliente sanitaria de 500L con doble serpentin para instalaciones comerciales',
    gallery: ['/product-acs.jpg', '/product-acs.jpg', '/product-acs.jpg'],
    quickSpecs: [
      { label: 'Capacidad', value: '500 L' },
      { label: 'Tipo de serpentin', value: 'Doble' },
      { label: 'Material', value: 'Acero inox 316' },
      { label: 'Presion maxima', value: '10 bar' },
      { label: 'Perdidas de carga', value: '32 mbar' },
      { label: 'Aislamiento', value: 'PU 70mm' },
      { label: 'Conexiones', value: 'G 1 1/2"' },
      { label: 'Peso vacio', value: '65 kg' },
      { label: 'Garantia', value: '5 anos' },
    ],
    benefits: [
      { icon: 'Droplets', title: 'CAPACIDAD COMERCIAL', description: '500 litros para restaurantes, gimnasios, hoteles pequenos y aplicaciones con alta demanda de agua caliente.' },
      { icon: 'Thermometer', title: 'MAXIMO AISLAMIENTO', description: '70mm de aislamiento de poliuretano de alta densidad para mantener el agua caliente por mas de 48 horas.' },
      { icon: 'Zap', title: 'DOBLE SERPENTIN EFICIENTE', description: 'Dos circuitos independientes permiten conectar simultaneamente bomba de calor y sistema solar termico.' },
      { icon: 'Shield', title: 'CONSTRUCCION INDUSTRIAL', description: 'Chapa de acero inoxidable 316 de 2mm de espesor con soldadura TIG certificada y prueba a 15 bar.' },
      { icon: 'Wrench', title: 'MANTENIMIENTO SIMPLE', description: 'Boca de acceso de 200mm para inspeccion y limpieza periodica. Anodo de sacrificio de larga duracion.' },
    ],
    docs: [
      { name: 'Ficha Tecnica ACS Pro 500L', format: 'PDF', size: '2.2 MB' },
      { name: 'Manual de Instalacion', format: 'PDF', size: '3.8 MB' },
      { name: 'Certificado Sanitario', format: 'PDF', size: '0.5 MB' },
    ],
    relatedSlugs: ['acs-pro-300l', 'acs-pro-200l', 'poolheat-20kw'],
  },
  'poolheat-12kw': {
    slug: 'poolheat-12kw',
    subtitle: 'Bomba de calor para piscinas de 12kW con intercambiador de titanio',
    gallery: ['/product-piscina.jpg', '/product-piscina.jpg', '/product-piscina.jpg'],
    quickSpecs: [
      { label: 'Potencia termica', value: '12 kW' },
      { label: 'Rango de temperatura', value: '20 - 32°C' },
      { label: 'Intercambiador', value: 'Titanio' },
      { label: 'COP', value: '5.8' },
      { label: 'Tension', value: '230V / 1Ph / 50Hz' },
      { label: 'Nivel sonoro', value: '40 dB(A)' },
      { label: 'Caudal maximo', value: '6 m3/h' },
      { label: 'Dimensiones', value: '850 x 350 x 580 mm' },
      { label: 'Garantia', value: '3 anos' },
    ],
    benefits: [
      { icon: 'Waves', title: 'TITANIO PURO', description: 'Intercambiador de calor en titanio grado 1 totalmente resistente a la corrosion del cloro y agua salada.' },
      { icon: 'Zap', title: 'COP 5.8', description: 'Eficiencia excepcional gracias a las condiciones favorables de temperatura de las piscinas. Ahorro de hasta 80%.' },
      { icon: 'VolumeX', title: 'ULTRA SILENCIOSO', description: 'Solo 40 dB(A). Compresor inverter y ventilador de flujo axial optimizado para minimo ruido.' },
      { icon: 'Thermometer', title: 'TODO EL ANO', description: 'Opera eficientemente con temperaturas ambiente de 5°C a 43°C. Ideal para climas tropicales y templados.' },
      { icon: 'Wrench', title: 'INSTALACION SENCILLA', description: 'Conexion directa a filtracion existente de la piscina. Bypass incluido con valvulas de bola.' },
    ],
    docs: [
      { name: 'Ficha Tecnica PoolHeat 12kW', format: 'PDF', size: '1.9 MB' },
      { name: 'Manual de Instalacion', format: 'PDF', size: '3.0 MB' },
      { name: 'Manual de Usuario', format: 'PDF', size: '1.2 MB' },
    ],
    relatedSlugs: ['poolheat-20kw', 'poolheat-35kw', 'aquapro-r32-8kw'],
  },
  'poolheat-20kw': {
    slug: 'poolheat-20kw',
    subtitle: 'Bomba de calor para piscinas de 20kW con intercambiador de titanio',
    gallery: ['/product-piscina.jpg', '/product-piscina.jpg', '/product-piscina.jpg'],
    quickSpecs: [
      { label: 'Potencia termica', value: '20 kW' },
      { label: 'Rango de temperatura', value: '20 - 35°C' },
      { label: 'Intercambiador', value: 'Titanio' },
      { label: 'COP', value: '5.5' },
      { label: 'Tension', value: '230V / 1Ph / 50Hz' },
      { label: 'Nivel sonoro', value: '43 dB(A)' },
      { label: 'Caudal maximo', value: '10 m3/h' },
      { label: 'Dimensiones', value: '980 x 380 x 650 mm' },
      { label: 'Garantia', value: '3 anos' },
    ],
    benefits: [
      { icon: 'Waves', title: 'TITANIO RESISTENTE', description: 'Intercambiador de titanio que soporta agua salada, clorada y tratada con ozono sin deterioro alguno.' },
      { icon: 'Zap', title: 'COP 5.5', description: 'Excelente eficiencia que reduce el costo de climatizar la piscina hasta un 80% vs sistemas electricos.' },
      { icon: 'VolumeX', title: 'OPERACION SILENCIOSA', description: 'Ventilador de paletas curvas y compresor inverter para una operacion discreta en zonas de descanso.' },
      { icon: 'Thermometer', title: 'RANGO EXTENDIDO', description: 'Capacidad de calentar piscinas de hasta 80m3 en climas templados y 50m3 en climas frios.' },
      { icon: 'Wrench', title: 'MANTENIMIENTO MINIMO', description: 'Carcasa de ABS anti-UV y componentes protegidos contra corrosion. Solo limpieza periodica del evaporador.' },
    ],
    docs: [
      { name: 'Ficha Tecnica PoolHeat 20kW', format: 'PDF', size: '2.1 MB' },
      { name: 'Manual de Instalacion', format: 'PDF', size: '3.3 MB' },
      { name: 'Manual de Usuario', format: 'PDF', size: '1.3 MB' },
    ],
    relatedSlugs: ['poolheat-12kw', 'poolheat-35kw', 'aquapro-r32-12kw'],
  },
  'poolheat-35kw': {
    slug: 'poolheat-35kw',
    subtitle: 'Bomba de calor para piscinas de 35kW con titanio e inverter para piscinas grandes',
    gallery: ['/product-piscina.jpg', '/product-piscina.jpg', '/product-piscina.jpg'],
    quickSpecs: [
      { label: 'Potencia termica', value: '35 kW' },
      { label: 'Rango de temperatura', value: '20 - 38°C' },
      { label: 'Intercambiador', value: 'Titanio + Inverter' },
      { label: 'COP', value: '5.2' },
      { label: 'Tension', value: '400V / 3Ph / 50Hz' },
      { label: 'Nivel sonoro', value: '48 dB(A)' },
      { label: 'Caudal maximo', value: '16 m3/h' },
      { label: 'Dimensiones', value: '1150 x 420 x 780 mm' },
      { label: 'Garantia', value: '3 anos' },
    ],
    benefits: [
      { icon: 'Waves', title: 'TITANIO + INVERTER', description: 'Intercambiador de titanio con compresor inverter para modulacion de potencia y maxima eficiencia en todo momento.' },
      { icon: 'Zap', title: 'COP 5.2', description: 'Eficiencia sostenida gracias a la modulacion inverter que adapta la potencia a la demanda real de la piscina.' },
      { icon: 'Box', title: 'PISCINAS GRANDES', description: '35 kW para piscinas de hasta 150m3 en climas templados y 100m3 en climas frios. Ideal para hoteles y clubs.' },
      { icon: 'Thermometer', title: 'TEMPERATURA 38°C', description: 'Capacidad de alcanzar 38°C para hidromasajes, spas y piscinas terapeuticas que requieren agua mas caliente.' },
      { icon: 'Wrench', title: 'CONTROL INTELIGENTE', description: 'Pantalla digital con programacion horaria, control de temperatura preciso y proteccion anti-hielo automatica.' },
    ],
    docs: [
      { name: 'Ficha Tecnica PoolHeat 35kW', format: 'PDF', size: '2.4 MB' },
      { name: 'Manual de Instalacion', format: 'PDF', size: '3.8 MB' },
      { name: 'Manual de Usuario', format: 'PDF', size: '1.5 MB' },
    ],
    relatedSlugs: ['poolheat-20kw', 'poolheat-12kw', 'aquapro-r32-20kw'],
  },
  'induheat-50kw': {
    slug: 'induheat-50kw',
    subtitle: 'Bomba de calor industrial de 50kW para procesos industriales y calefaccion comercial',
    gallery: ['/product-industrial.jpg', '/product-industrial.jpg', '/product-industrial.jpg'],
    quickSpecs: [
      { label: 'Potencia termica', value: '50 kW' },
      { label: 'COP (A15/W45)', value: '4.2' },
      { label: 'Aplicacion', value: 'Procesos industriales' },
      { label: 'Temperatura max. salida', value: '75°C' },
      { label: 'Tension', value: '400V / 3Ph / 50Hz' },
      { label: 'Nivel sonoro', value: '58 dB(A)' },
      { label: 'Peso', value: '285 kg' },
      { label: 'Dimensiones', value: '1550 x 700 x 1250 mm' },
      { label: 'Garantia', value: '5 anos' },
    ],
    benefits: [
      { icon: 'Zap', title: 'ALTA TEMPERATURA', description: '75°C de salida para procesos industriales que requieren agua caliente de alta temperatura.' },
      { icon: 'Box', title: 'PROCESOS INDUSTRIALES', description: 'Ideal para lavanderias industriales, plantas de alimentos, procesos quimicos y calefaccion de grandes naves.' },
      { icon: 'Thermometer', title: 'FUNCIONA TODO EL ANO', description: 'Compresor de alta cilindrada que mantiene el rendimiento a temperaturas ambiente de hasta -20°C.' },
      { icon: 'Wrench', title: 'CONTROL INDUSTRIAL', description: 'Automatizacion completa con entradas/salidas para integracion en sistemas SCADA y BMS.' },
      { icon: 'Shield', title: 'GARANTIA 5 ANOS', description: 'Soporte tecnico especializado con respuesta en 24h y stock de repuestos en todos los paises de operacion.' },
    ],
    docs: [
      { name: 'Ficha Tecnica InduHeat 50kW', format: 'PDF', size: '3.0 MB' },
      { name: 'Manual de Instalacion Industrial', format: 'PDF', size: '7.2 MB' },
      { name: 'Manual de Control y Automatizacion', format: 'PDF', size: '2.8 MB' },
      { name: 'Certificado CE', format: 'PDF', size: '0.6 MB' },
    ],
    relatedSlugs: ['inducascade-150kw', 'geomax-40kw', 'geomax-cascade-50kw'],
  },
  'inducascade-150kw': {
    slug: 'inducascade-150kw',
    subtitle: 'Sistema industrial en cascada de 150kW para grandes volumenes y aplicaciones criticas',
    gallery: ['/product-industrial.jpg', '/product-industrial.jpg', '/product-industrial.jpg'],
    quickSpecs: [
      { label: 'Potencia termica', value: '150 kW' },
      { label: 'COP (A15/W45)', value: '3.8' },
      { label: 'Aplicacion', value: 'Gran volumen' },
      { label: 'Temperatura max. salida', value: '80°C' },
      { label: 'Tension', value: '400V / 3Ph / 50Hz' },
      { label: 'Nivel sonoro', value: '65 dB(A)' },
      { label: 'Peso', value: '780 kg' },
      { label: 'Dimensiones', value: '2400 x 900 x 1800 mm' },
      { label: 'Garantia', value: '5 anos' },
    ],
    benefits: [
      { icon: 'Zap', title: 'POTENCIA MASIVA', description: '150 kW en configuracion de cascada modular para grandes edificios, hoteles, hospitales y procesos industriales.' },
      { icon: 'Box', title: 'REDUNDANCIA TOTAL', description: 'Sistema de 4 unidades modulares que permite mantener el 75% de capacidad durante mantenimiento de cualquier modulo.' },
      { icon: 'Thermometer', title: '80°C DE SALIDA', description: 'Temperatura de salida de hasta 80°C compatible con sistemas de calefaccion de alta temperatura y procesos industriales.' },
      { icon: 'Wrench', title: 'SOPORTE DEDICADO', description: 'Ingeniero de cuenta asignado con soporte 24/7, mantenimiento preventivo trimestral y visitas anuales de revision.' },
      { icon: 'Shield', title: 'VIDA UTIL 20+ ANOS', description: 'Construccion industrial con componentes de grado militar, chapa galvanizada y pintura epoxi resistente a ambientes agresivos.' },
    ],
    docs: [
      { name: 'Ficha Tecnica InduCascada 150kW', format: 'PDF', size: '4.5 MB' },
      { name: 'Manual de Instalacion Industrial', format: 'PDF', size: '9.8 MB' },
      { name: 'Manual de Control y Automatizacion', format: 'PDF', size: '3.5 MB' },
      { name: 'Certificado CE', format: 'PDF', size: '0.8 MB' },
    ],
    relatedSlugs: ['induheat-50kw', 'geomax-cascade-50kw', 'geomax-40kw'],
  },
};
