export interface Product {
  id: string;
  model: string;
  name: string;
  nameEn: string;
  category: "acs" | "clima" | "pool" | "commercial" | "accessory";
  type: string;
  compressors: number;
  power: number; // kW
  flowRate: number; // L/h o m³/h
  temperature: number; // °C
  capacity: string;
  voltage: string;
  refrigerant: string;
  dimensions: string;
  weight: number; // kg
  noise: string;
  image: string;
  solarCompatible: boolean;
  description: string;
  applications: string[];
  certifications: string[];
}

export const products: Product[] = [
  // LÍNEA ACS - HORIZONTAL
  {
    id: "obt-050",
    model: "OBT-050-DKFXRS",
    name: "Bomba de Calor Horizontal 5P",
    nameEn: "Horizontal Heat Pump 5P",
    category: "acs",
    type: "ACS + 60°",
    compressors: 1,
    power: 17.8,
    flowRate: 383,
    temperature: 60,
    capacity: "5.000 litros/día",
    voltage: "380V / 3N / 50Hz",
    refrigerant: "R410A / 1.900 g",
    dimensions: "750 × 750 × 1100 mm",
    weight: 120,
    noise: "≤ 58 dB(A)",
    image: "/products/5P.jpg",
    solarCompatible: true,
    description: "Calienta estanque de 5.000 litros de agua al día. Consumo eléctrico: 4,5 kWh. Producción continua de ACS para consumo diario del edificio. Operación estable en sistemas centralizados.",
    applications: ["Edificios residenciales", "Hoteles", "Gimnasios", "Hospitales"],
    certifications: ["TÜV Rheinland", "CE", "MCS"],
  },
  {
    id: "obt-070",
    model: "OBT-070-DKFXRS",
    name: "Bomba de Calor Horizontal 7P",
    nameEn: "Horizontal Heat Pump 7P",
    category: "acs",
    type: "ACS + 60°",
    compressors: 1,
    power: 22.3,
    flowRate: 499,
    temperature: 60,
    capacity: "5.000 litros/día",
    voltage: "380V / 3N / 50Hz",
    refrigerant: "R410A / 2.500 g",
    dimensions: "750 × 750 × 1100 mm",
    weight: 155,
    noise: "≤ 58 dB(A)",
    image: "/products/5P.jpg",
    solarCompatible: true,
    description: "Calienta estanque de 5.000 litros de agua al día. Consumo eléctrico: 5,4 kWh. Mayor capacidad térmica para proyectos de mayor demanda.",
    applications: ["Edificios comerciales", "Condominios", "Industria alimentaria"],
    certifications: ["TÜV Rheinland", "CE", "MCS"],
  },
  {
    id: "obt-100h",
    model: "OBT-100-DKFXRS",
    name: "Bomba de Calor Horizontal 10P",
    nameEn: "Horizontal Heat Pump 10P",
    category: "acs",
    type: "ACS + 60°",
    compressors: 2,
    power: 35.6,
    flowRate: 766,
    temperature: 60,
    capacity: "10.000 litros/día",
    voltage: "380V / 3N / 50Hz",
    refrigerant: "R410A / 1.900 g × 2",
    dimensions: "1500 × 690 × 1060 mm",
    weight: 240,
    noise: "≤ 58 dB(A)",
    image: "/products/10P-1.jpg",
    solarCompatible: true,
    description: "Calienta estanque de 10.000 litros de agua al día. Consumo eléctrico: 9,0 kWh. Doble compresor para mayor redundancia y capacidad.",
    applications: ["Grandes edificios", "Hoteles", "Centros deportivos", "Industria"],
    certifications: ["TÜV Rheinland", "CE", "MCS"],
  },
  {
    id: "obt-120h",
    model: "OBT-120-DKFXRS",
    name: "Bomba de Calor Horizontal 12P",
    nameEn: "Horizontal Heat Pump 12P",
    category: "acs",
    type: "ACS + 60°",
    compressors: 2,
    power: 42,
    flowRate: 902,
    temperature: 60,
    capacity: "10.000 litros/día",
    voltage: "380V / 3N / 50Hz",
    refrigerant: "R410A / 2.200 g × 2",
    dimensions: "1500 × 690 × 1060 mm",
    weight: 260,
    noise: "≤ 58 dB(A)",
    image: "/products/10P-1.jpg",
    solarCompatible: true,
    description: "Calienta estanque de 10.000 litros de agua al día. Consumo eléctrico: 10,2 kWh. Máxima capacidad de la línea horizontal.",
    applications: ["Grandes edificios", "Hospitales", "Industria", "Centros deportivos"],
    certifications: ["TÜV Rheinland", "CE", "MCS"],
  },
  // LÍNEA ACS - VERTICAL
  {
    id: "obt-100v",
    model: "OBT-100-DKFXRS (Vertical)",
    name: "Bomba de Calor Vertical 10P",
    nameEn: "Vertical Heat Pump 10P",
    category: "acs",
    type: "ACS + 60°",
    compressors: 1,
    power: 38.6,
    flowRate: 830,
    temperature: 60,
    capacity: "10.000 litros/día",
    voltage: "380V / 3N / 50Hz",
    refrigerant: "R410A / 6.500 g",
    dimensions: "854 × 854 × 1920 mm",
    weight: 320,
    noise: "≤ 66 dB(A)",
    image: "/products/3.png",
    solarCompatible: true,
    description: "Calienta estanque de 10.000 litros de agua al día. Consumo eléctrico: 9,38 kWh. Diseño vertical para espacios reducidos en azoteas.",
    applications: ["Edificios con poco espacio", "Azoteas", "Sala de máquinas"],
    certifications: ["TÜV Rheinland", "CE"],
  },
  {
    id: "obt-120v",
    model: "OBT-120-DKFXRS (Vertical)",
    name: "Bomba de Calor Vertical 12P",
    nameEn: "Vertical Heat Pump 12P",
    category: "acs",
    type: "ACS + 60°",
    compressors: 1,
    power: 44.2,
    flowRate: 950,
    temperature: 60,
    capacity: "10.000 litros/día",
    voltage: "380V / 3N / 50Hz",
    refrigerant: "R410A / 7.000 g",
    dimensions: "854 × 854 × 1920 mm",
    weight: 340,
    noise: "≤ 66 dB(A)",
    image: "/products/3.png",
    solarCompatible: true,
    description: "Calienta estanque de 10.000 litros de agua al día. Consumo eléctrico: 10,72 kWh. Máxima capacidad vertical.",
    applications: ["Grandes edificios", "Hoteles", "Industria"],
    certifications: ["TÜV Rheinland", "CE"],
  },
  // LÍNEA PISCINA
  {
    id: "pool-050",
    model: "DKFXRS-050H-HW",
    name: "Bomba de Calor Piscina 5P",
    nameEn: "Pool Heat Pump 5P",
    category: "pool",
    type: "Piscina +28°",
    compressors: 1,
    power: 20.5,
    flowRate: 6,
    temperature: 28,
    capacity: "32 m³ con cobertor",
    voltage: "380V / 3N / 50Hz",
    refrigerant: "R410A",
    dimensions: "750 × 750 × 1100 mm",
    weight: 150,
    noise: "≤ 60 dB(A)",
    image: "/products/14.jpg",
    solarCompatible: true,
    description: "Climatización eficiente para piscinas (setpoint 28°C). Consumo eléctrico: 4,0 kW. Compatible con filtración y circuito hidráulico existente.",
    applications: ["Piscinas residenciales", "Piscinas hoteleras", "Spas"],
    certifications: ["CE", "TÜV Rheinland"],
  },
  {
    id: "pool-100",
    model: "DKFXRS-100H-HW",
    name: "Bomba de Calor Piscina 10P",
    nameEn: "Pool Heat Pump 10P",
    category: "pool",
    type: "Piscina +28°",
    compressors: 2,
    power: 45,
    flowRate: 12.9,
    temperature: 28,
    capacity: "72 m³ con cobertor",
    voltage: "380V / 3N / 50Hz",
    refrigerant: "R410A",
    dimensions: "1500 × 700 × 1100 mm",
    weight: 280,
    noise: "≤ 66 dB(A)",
    image: "/products/14.jpg",
    solarCompatible: true,
    description: "Climatización eficiente para piscinas grandes (setpoint 28°C). Consumo eléctrico: 8,2 kW. Doble compresor para mayor capacidad.",
    applications: ["Piscinas olímpicas", "Centros deportivos", "Hoteles 5 estrellas"],
    certifications: ["CE", "TÜV Rheinland"],
  },
  // LÍNEA CLIMATIZACIÓN ALL-IN-ONE
  {
    id: "clima-050",
    model: "DKFXRS-050H",
    name: "Bomba All-in-One Climatización 5P",
    nameEn: "All-in-One Climate 5P",
    category: "clima",
    type: "Frío/Calor",
    compressors: 1,
    power: 5,
    flowRate: 0,
    temperature: 0,
    capacity: "100-110 m²",
    voltage: "220V / 1N / 50Hz",
    refrigerant: "R410A",
    dimensions: "1600 × 700 × 1500 mm",
    weight: 0,
    noise: "≤ 55 dB(A)",
    image: "/products/1000345519.jpg",
    solarCompatible: true,
    description: "Trabaja con radiadores y/o fancoil para 120 m². Incluye estanque buffer presurizado de 60 L. Incluye bomba de circulación Wilo PUN-201. Solución compacta all-in-one.",
    applications: ["Casas unifamiliares", "Departamentos", "Oficinas"],
    certifications: ["CE"],
  },
  {
    id: "clima-080",
    model: "DKFXRS-080H",
    name: "Bomba All-in-One Climatización 8P",
    nameEn: "All-in-One Climate 8P",
    category: "clima",
    type: "Frío/Calor",
    compressors: 1,
    power: 8,
    flowRate: 0,
    temperature: 0,
    capacity: "150-160 m²",
    voltage: "220V / 1N / 50Hz",
    refrigerant: "R410A",
    dimensions: "1800 × 700 × 1800 mm",
    weight: 0,
    noise: "≤ 55 dB(A)",
    image: "/products/1000345519.jpg",
    solarCompatible: true,
    description: "Trabaja con radiadores y/o fancoil para 150 m². Incluye estanque buffer presurizado de 120 L. Incluye bomba de circulación Wilo PUN-601.",
    applications: ["Casas grandes", "Departamentos premium", "Oficinas"],
    certifications: ["CE"],
  },
  {
    id: "clima-100",
    model: "DKFXRS-100H",
    name: "Bomba All-in-One Climatización 10P",
    nameEn: "All-in-One Climate 10P",
    category: "clima",
    type: "Frío/Calor",
    compressors: 1,
    power: 10,
    flowRate: 0,
    temperature: 0,
    capacity: "200-220 m²",
    voltage: "380V / 3N / 50Hz",
    refrigerant: "R410A",
    dimensions: "2400 × 1000 × 1900 mm",
    weight: 0,
    noise: "≤ 58 dB(A)",
    image: "/products/1000345519.jpg",
    solarCompatible: true,
    description: "Trabaja con radiadores y/o fancoil para 200 m². Incluye estanque buffer presurizado de 150 L. Incluye bomba de circulación Wilo PUN-750.",
    applications: ["Casas grandes", "Edificios pequeños", "Locales comerciales"],
    certifications: ["CE"],
  },
  // LÍNEA COMERCIAL/INDUSTRIAL - INVERTER
  {
    id: "cgk-52",
    model: "CGK/D-52",
    name: "Bomba de Calor Comercial R410A",
    nameEn: "Commercial Heat Pump R410A",
    category: "commercial",
    type: "Monoblock",
    compressors: 2,
    power: 52,
    flowRate: 9936,
    temperature: 55,
    capacity: "52 kW",
    voltage: "380V / 3N / 50Hz",
    refrigerant: "R410A",
    dimensions: "1500 × 800 × 1150 mm",
    weight: 300,
    noise: "68 dB",
    image: "/products/Maquina PSL 700.jpg",
    solarCompatible: true,
    description: "Heating capacity: 52 kW (A20°C/W55°C). Controlador SPRSUN múltiples funciones. Working mode: Hot water. Compresores Copeland scroll INVOTECH.",
    applications: ["Hoteles", "Hospitales", "Industria", "Grandes edificios"],
    certifications: ["CE", "TÜV Rheinland"],
  },
  {
    id: "cgk-151v4",
    model: "CGK-151V4-B",
    name: "Bomba Inverter R290 50kW",
    nameEn: "DC Inverter Heat Pump R290 50kW",
    category: "commercial",
    type: "DC Inverter",
    compressors: 1,
    power: 50,
    flowRate: 8.6,
    temperature: 70,
    capacity: "50 kW",
    voltage: "380-420V / 3N / 50Hz",
    refrigerant: "R290 / 4.5 kg",
    dimensions: "1187 × 1087 × 1680 mm",
    weight: 375,
    noise: "70.7 dB(A)",
    image: "/products/Maquina PSL 700.jpg",
    solarCompatible: true,
    description: "DC Inverter. Heating capacity: 50 kW (A7°C/W35°C). COP: 3.80. Compresor Panasonic Rotary. Touch screen controller. Modos: hot water/heating/cooling.",
    applications: ["Edificios comerciales", "Industria", "Hoteles"],
    certifications: ["A++", "A+++"],
  },
  {
    id: "cgk-300v4",
    model: "CGK-300V4-B",
    name: "Bomba Inverter R290 100kW",
    nameEn: "DC Inverter Heat Pump R290 100kW",
    category: "commercial",
    type: "DC Inverter",
    compressors: 2,
    power: 100,
    flowRate: 17.2,
    temperature: 70,
    capacity: "100 kW",
    voltage: "380-420V / 3N / 50Hz",
    refrigerant: "R290 / 2×3.8 kg",
    dimensions: "2200 × 1100 × 1966 mm",
    weight: 760,
    noise: "75 dB(A)",
    image: "/products/Maquina PSL 700.jpg",
    solarCompatible: true,
    description: "DC Inverter. Heating capacity: 100 kW (A7°C/W35°C). COP: 3.75. Compresor Panasonic Rotary ×2. Touch screen controller. Modos: hot water/heating/cooling.",
    applications: ["Grandes edificios", "Industria", "Centros deportivos"],
    certifications: ["A++", "A+++"],
  },
  {
    id: "cgk-150v3",
    model: "CGK-150V3L-B",
    name: "Bomba Inverter R32 45kW",
    nameEn: "DC Inverter Heat Pump R32 45kW",
    category: "commercial",
    type: "DC Inverter",
    compressors: 2,
    power: 45.1,
    flowRate: 7.76,
    temperature: 55,
    capacity: "45.1 kW",
    voltage: "380-420V / 3N / 50Hz",
    refrigerant: "R32",
    dimensions: "1400 × 525 × 1570 mm",
    weight: 260,
    noise: "53.2-63.6 dB(A)",
    image: "/products/Maquina PSL 700.jpg",
    solarCompatible: true,
    description: "DC Inverter. Heating capacity: 45.1 kW (A7°C/W35°C). COP: 4.2. Compresor Panasonic Twin Rotary. Touch screen controller. Modos: hot water/heating/cooling.",
    applications: ["Edificios comerciales", "Hoteles", "Industria"],
    certifications: ["A++", "A+++"],
  },
  // ACCESORIOS
  {
    id: "est-cuad",
    model: "Estanque Cuadrado",
    name: "Estanque Cuadrado de Acero Inoxidable",
    nameEn: "Square Stainless Steel Tank",
    category: "accessory",
    type: "Acumulación",
    compressors: 0,
    power: 0,
    flowRate: 0,
    temperature: 0,
    capacity: "1-10 m³",
    voltage: "N/A",
    refrigerant: "N/A",
    dimensions: "2.5 × 2 × 1 m (5m³)",
    weight: 0,
    noise: "N/A",
    image: "/products/ACUMULADOR BLOQUES 2.png",
    solarCompatible: true,
    description: "Estanque abierto, liviano y sanitario para acumulación sin presión. Acero inoxidable sanitario. Formato modular para armado en sitio. Ideal para proyectos con bombas de calor.",
    applications: ["ACS en edificios", "Proyectos con menor carga estructural", "Montaje en salas de calderas"],
    certifications: ["Sanitario"],
  },
  {
    id: "est-cil",
    model: "Estanque Cilíndrico",
    name: "Estanque Cilíndrico de Acero Inoxidable",
    nameEn: "Cylindrical Stainless Steel Tank",
    category: "accessory",
    type: "Acumulación",
    compressors: 0,
    power: 0,
    flowRate: 0,
    temperature: 0,
    capacity: "1-10 m³",
    voltage: "N/A",
    refrigerant: "N/A",
    dimensions: "Ø 1.75 × 2.4 m (5m³)",
    weight: 0,
    noise: "N/A",
    image: "/products/estanque.jpg",
    solarCompatible: true,
    description: "Estanque abierto, liviano y sanitario, listo para instalar. Acero inoxidable sanitario con aislación térmica. Montaje rápido y ordenado para proyectos ACS.",
    applications: ["ACS en edificios", "Reemplazo de estanques antiguos", "Proyectos con instalación rápida"],
    certifications: ["Sanitario"],
  },
];

export const categories = [
  { id: "acs", label: "Agua Caliente Sanitaria", labelEn: "Hot Water" },
  { id: "clima", label: "Climatización", labelEn: "Climate" },
  { id: "pool", label: "Piscina", labelEn: "Pool" },
  { id: "commercial", label: "Comercial/Industrial", labelEn: "Commercial" },
  { id: "accessory", label: "Accesorios", labelEn: "Accessories" },
];
